### ISSUE TITLE
Errors in libraries with only terminology declarations are not displayed

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/vscode-cql#5] opened 2022-01-04 00:06 UTC
For example the [ColorectalCancerConcepts](https://github.com/cqframework/cqf-ccc/blob/master/input/cql/ColorectalCancerConcepts.cql) library

The translation is happening and other libraries that depend on the concepts library do report errors so that's all working just something about a library without any expression defs is causing the errors not to be reported correctly.

Note also that the Atom plu9gin does not exhibit this behavior, so it's something specific to the vscode plugin.

**Comment by JPercival** [comment] 2022-01-10 22:00
Root cause was off by one index error for displaying messages. Resolved in release 0.1.3.

It does seem like the cql-translator is not reporting erroneous syntax as accurately as it used to.

**Closed by JPercival** 2022-01-10 22:00 UTC
Labels: bug, good first issue
