### ISSUE TITLE
CQL Plug-in issue after update 8/10/22

### ISSUE THREAD

**Issue by DrMuir** [cqframework/vscode-cql#17] opened 2022-08-11 20:44 UTC
VScode (Linux/Ubuntu) not working properly on previously working measures/data in local  r4-2021 and QI-Core 2022 since CQL plug-in updated 8/10. 
Released on 9/24/2021, 16:40:12
Last updated 8/10/2022, 12:09:45
Identifier cqframework.cql

Will try delete and reload of plug.

**Comment by JSRankins** [comment] 2022-08-11 21:53
Having similar problems in Windows 10 and 11 environments, even while working in Docker environment.

**Comment by DrMuir** [comment] 2022-08-12 14:01
After I deleted plug-in v0.1.5 and reinstalled v0.1.4, it is running appropriately again.  Presumably, I am missing some other requirement but will stay old school for now.

**Comment by c-schuler** [comment] 2022-08-12 22:27
@DrMuir could you provide more information on what is not working properly. I have been able to run several of the measures in the https://github.com/cqframework/ecqm-content-r4-2021 IG successfully.

**Comment by matthewtiller** [comment] 2022-08-12 22:28
Same thing with me, Windows 11.

It would take a long time upon startup to initialize and recognize errors/issues, and only simple measures would work with Execute CQL.

One bit of new weird behavior I noticed was that it would flag CQL libraries as duplicate across different projects. For example, a copy of FHIRHelpers in one project would be considered a duplicate of FHIRHelpers in a completely different project if they were both loaded in the project explorer at the same time.

**Comment by frankadrian314159** [comment] 2022-08-15 15:48
Upgraded to VSCode 1.70 on Windows 10 this morning (2022/08/15). Started getting startup messages from V0.1.5 of CQL extension:
Error: Invalid or corrupt jarfile c:\Users\fadrian\.vscode\extensions\cqframework.cql-0.1.5\dist\jars\cql-ls-service-1.5.7.jar
[Info  - 8:19:12 AM] Connection to server got closed. Server will restart.

After removing the CQL extension from the .vscode/extensions folder and re-installing the extension, things seem to work again.

**Comment by JSRankins** [comment] 2022-08-22 17:29
Still having issues even after removing CQL extension and reinstalling. 
On Windows 10
On VS Code 1.70.2

Highlighting works, but validation will not work.

**Comment by matthewtiller** [comment] 2022-08-23 13:21
It automatically upgraded to 0.1.6 pre-release version and seemed to work well. But the next day, after I removed older versions of the extension and a restart, it stopped working. "Execute CQL" seems to do nothing -- no results file opens, and no java thread is started in the task manager. I've tried uninstalling the extension and re-installing, and nothing happens. I have confirmed that the 1.5.8 jar is in place for 0.1.6.

On the bright side, 0.1.5 is working and seems to be performing somewhat better.

**Comment by brynrhodes** [comment] 2022-09-06 15:13
These issues should all be addressed with the 0.2.0 release

**Closed by brynrhodes** 2022-09-06 15:13 UTC

**Comment by DrMuir** [comment] 2022-10-11 09:23
Hey Stan.  I uninstalled VScode 0.1.5 plug-in and went back to 0.1.4 which resolved run issue.  I suspect there is something out of alignment with the CQL-language server at this time.


Peter Muir | MD ABFM FCFP  Informatics
ESAC, now proudly part of ICF
Note new email: ***@***.******@***.***>
icf.com<https://www.icf.com/>

________________________________
